// Package idempotency is the §8(c) retry-safety cache seam for the Go worker.
//
// finalplanv2.md §8(c): once retries-with-backoff exist on the FastAPI→Go
// call, a timeout that actually completed work would double-process on retry.
// The fix is a short-TTL cache keyed on the ParseRequest.idempotency_key
// ({job_id}:{source_id}, generated by FastAPI): before parsing, the worker
// checks the store; a hit returns the cached ParseResponse bytes verbatim,
// a miss parses and writes the result under the key.
//
// The plan pins Redis ("redis-go/v9 at deployment" — see golang/dep_notes.go)
// and calls for a distinct keyspace prefix.  This package owns that prefix
// ("idemp:") and the Store seam; the Memory store shipped here is strictly
// the hermetic implementation that makes the retry-safety semantics provable
// with `make test-go` (zero sockets).  A Redis store must implement the same
// interface and must not change the wire bytes cached here.
package idempotency

import (
	"context"
	"sync"
	"time"
)

// Namespace is the Redis keyspace prefix for idempotency state (§8
// "Keyspace separation": ratelimit:, job:, idemp:).  Every store prepends
// it, so a debugging KEYS * scan can tell subsystems apart.
const Namespace = "idemp:"

// TTL is how long a cached ParseResponse is considered the retry-able
// result.  The plan says "short TTL … e.g. a few minutes — this is not a
// durability store, Postgres already owns that".
const TTL = 5 * time.Minute

// CacheKey derives the full key for one idempotency_key.
func CacheKey(idempotencyKey string) string {
	return Namespace + idempotencyKey
}

// Store is the idempotency cache seam.  A Redis-backed implementation will
// implement this at the deployment slice; everything in the hermetic proofs
// runs against Memory.  Callers treat Get/Set errors as best-effort: the
// worker must still parse when the cache is unavailable (availability over
// dedup — see golang/httpapi).
type Store interface {
	// Get returns the cached ParseResponse bytes for key, or ok==false when
	// absent/expired.
	Get(ctx context.Context, key string) (data []byte, ok bool, err error)
	// Set stores the ParseResponse bytes under key for ttl.
	Set(ctx context.Context, key string, data []byte, ttl time.Duration) error
}

// Memory is the hermetic in-process Store used by tests and single-instance
// runs.  Keys live under Namespace; entries expire on read or when a timer
// naturally reaps them.  Not for multi-instance deployment — Redis is the
// shared-state answer there (§8).
type Memory struct {
	mu    sync.Mutex
	clock func() time.Time
	data  map[string]memoryEntry
}

type memoryEntry struct {
	data    []byte
	expires time.Time
}

// NewMemory returns a Memory store with the given wall clock (nil ==
// time.Now).  The clock is injectable so TTL expiry is testable hermetically.
func NewMemory(clock func() time.Time) *Memory {
	if clock == nil {
		clock = time.Now
	}
	return &Memory{
		clock: clock,
		data:  make(map[string]memoryEntry),
	}
}

// Get implements Store.  Expired entries are removed lazily on read.
func (m *Memory) Get(ctx context.Context, key string) ([]byte, bool, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	full := CacheKey(key)
	e, ok := m.data[full]
	if !ok {
		return nil, false, nil
	}
	if !m.clock().Before(e.expires) {
		delete(m.data, full)
		return nil, false, nil
	}
	return e.data, true, nil
}

// Set implements Store.
func (m *Memory) Set(ctx context.Context, key string, data []byte, ttl time.Duration) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.data[CacheKey(key)] = memoryEntry{
		data:    append([]byte(nil), data...),
		expires: m.clock().Add(ttl),
	}
	return nil
}
