"""cookies.txt parsing + the POST /api/accounts/cookies-txt endpoint."""
from __future__ import annotations

import pytest

from backend.scraper.browser_scraper import save_cookies
from backend.scraper.cookies_txt import (
    InvalidCookiesTxt,
    parse_cookies_txt,
    require_facebook_session,
)
from helpers import error_envelope

_SESSION_TXT = """# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by Get cookies.txt LOCALLY

# facebook.com\tTRUE\t/\tFALSE\t0\tfr\t0sJfZd...
.facebook.com\tTRUE\t/\tFALSE\t0\twd\t1234
#HttpOnly_.facebook.com\tTRUE\t/\tFALSE\t0\tdpr\t2
.facebook.com\tTRUE\t/\tTRUE\t1863317412\tc_user\t1000001
#HttpOnly_.facebook.com\tTRUE\t/\tTRUE\t1863317412\txs\tsecret-token
# trailing comment-only line
"""

_VALID_COOKIES = [
    {
        "name": "c_user", "value": "1001", "domain": ".facebook.com", "path": "/",
        "expires": 4102444800, "secure": True, "httpOnly": True,
    },
    {
        "name": "xs", "value": "sess-token", "domain": ".facebook.com", "path": "/",
        "expires": 4102444800, "secure": True, "httpOnly": True,
    },
]


def _user_id(firebase_uid: str) -> int:
    from backend.core.database import SessionLocal
    from backend.models import User

    with SessionLocal() as db:
        user = db.query(User).filter_by(firebase_uid=firebase_uid).first()
        assert user is not None, f"user {firebase_uid} was not provisioned"
        return user.id


# ---------------------------------------------------------------------------
# parser unit tests
# ---------------------------------------------------------------------------


class TestParseCookiesTxt:
    def test_parses_full_export(self):
        cookies = parse_cookies_txt(_SESSION_TXT)
        assert len(cookies) == 4

        by_name = {c["name"]: c for c in cookies}
        assert by_name["wd"] == {
            "name": "wd", "value": "1234", "domain": ".facebook.com", "path": "/",
            "expires": -1, "httpOnly": False, "secure": False, "sameSite": "Lax",
        }
        # #HttpOnly_ rows keep httpOnly + secure flags and the timestamp.
        assert by_name["xs"]["httpOnly"] is True
        assert by_name["xs"]["secure"] is True
        assert by_name["xs"]["expires"] == 1863317412
        assert by_name["c_user"]["value"] == "1000001"
        # Netscape "0" (session cookie) maps to Playwright -1.
        assert by_name["dpr"]["expires"] == -1

    def test_accepts_crlf_line_endings(self):
        text = _SESSION_TXT.replace("\n", "\r\n")
        assert len(parse_cookies_txt(text)) == 4

    def test_skips_malformed_rows_but_keeps_valid_ones(self):
        text = (
            ".facebook.com\tTRUE\t/\tFALSE\t0\tname\tvalue\n"
            "just-a-garbage-line\n"
            ".facebook.com\tTRUE\n"
            "#HttpOnly_.facebook.com\tTRUE\t/\tTRUE\t0\txs\tsecret\n"
        )
        cookies = parse_cookies_txt(text)
        assert [c["name"] for c in cookies] == ["name", "xs"]

    def test_rejects_empty_input(self):
        with pytest.raises(InvalidCookiesTxt, match="empty"):
            parse_cookies_txt("")
        with pytest.raises(InvalidCookiesTxt, match="empty"):
            parse_cookies_txt("   \n  \n")

    def test_rejects_content_with_no_valid_rows(self):
        with pytest.raises(InvalidCookiesTxt, match="No cookies"):
            parse_cookies_txt("# Netscape HTTP Cookie File\n# only comments here\n")

    def test_require_facebook_session_passes_for_valid_jar(self):
        require_facebook_session(parse_cookies_txt(_SESSION_TXT))  # no raise

    def test_require_facebook_session_rejects_without_xs(self):
        text = _SESSION_TXT.replace("#HttpOnly_.facebook.com\tTRUE\t/\tTRUE\t1863317412\txs\tsecret-token\n", "")
        with pytest.raises(InvalidCookiesTxt, match="xs"):
            require_facebook_session(parse_cookies_txt(text))

    def test_require_facebook_session_rejects_without_c_user(self):
        cookies = parse_cookies_txt(_SESSION_TXT)
        cookies = [c for c in cookies if c["name"] != "c_user"]
        with pytest.raises(InvalidCookiesTxt, match="c_user"):
            require_facebook_session(cookies)


# ---------------------------------------------------------------------------
# endpoint tests
# ---------------------------------------------------------------------------


def test_cookies_txt_endpoint_requires_auth(client):
    resp = client.post("/api/accounts/cookies-txt", json={"name": "x", "cookies_txt": "whatever"})
    assert resp.status_code == 401


def test_me_flow_creates_a_saved_session(authed_client):
    authed_client.get("/api/auth/me")  # provision user A
    resp = authed_client.post(
        "/api/accounts/cookies-txt",
        json={"name": "pasted", "scope": "me", "cookies_txt": _SESSION_TXT},
    )
    assert resp.status_code == 201
    body = resp.json()
    assert body["name"] == "pasted"
    assert body["scope"] == "me"
    assert body["status"] == "VALID"

    mine = authed_client.get("/api/accounts").json()["mine"]
    assert [a["name"] for a in mine] == ["pasted"]


def test_invalid_format_returns_400_with_clear_code(authed_client):
    authed_client.get("/api/auth/me")
    resp = authed_client.post(
        "/api/accounts/cookies-txt",
        json={"name": "bad", "scope": "me", "cookies_txt": "definitely not cookies.txt"},
    )
    assert resp.status_code == 400
    assert resp.json()["error"]["code"] == "invalid_cookies_file"
    error_envelope(resp.json())


def test_missing_facebook_session_cookie_returns_400(authed_client):
    authed_client.get("/api/auth/me")
    # A valid cookies.txt that simply never held a Facebook session.
    text = ".example.com\tTRUE\t/\tFALSE\t0\tsome_cookie\tvalue\n"
    resp = authed_client.post(
        "/api/accounts/cookies-txt",
        json={"name": "wrong", "scope": "me", "cookies_txt": text},
    )
    assert resp.status_code == 400
    assert resp.json()["error"]["code"] == "invalid_cookies_file"
    assert "c_user" in resp.json()["error"]["message"]


def test_ops_scope_requires_the_ops_role(authed_client):
    resp = authed_client.post(
        "/api/accounts/cookies-txt",
        json={"name": "shared", "scope": "ops", "cookies_txt": _SESSION_TXT},
    )
    assert resp.status_code == 403
    assert resp.json()["error"]["code"] == "admin_required"


def test_me_flow_respects_the_plan_cap(authed_client):
    authed_client.get("/api/auth/me")  # provision user A (basic plan, cap 1)
    owner_id = _user_id("test_firebase_uid_user_a")
    save_cookies(list(_VALID_COOKIES), account_name="one", owner_id=owner_id)

    resp = authed_client.post(
        "/api/accounts/cookies-txt",
        json={"name": "two", "scope": "me", "cookies_txt": _SESSION_TXT},
    )
    assert resp.status_code == 429
    assert resp.json()["error"]["code"] == "plan_limit"